export interface AdvisorCategory {
  id: number;
  name: string;
  icon: string;
  gradient: string[];
  isPopular: boolean;
  bgColor: string;
  color: string;
  categories: {
    id: number;
    title: string;
    tags: string[];
    icon: string;
    recommendedQuestions: string[];
  }[];
}

export const ADVISOR_CATEGORIES: Record<string, AdvisorCategory> = {
  nutrition: {
    id: 1,
    name: "Nutrition & Diet",
    icon: "Salad",
    gradient: ["#6EE7B7", "#10B981"],
    isPopular: true,
    bgColor: "#CCFBF1",
    color: "#0D9488",
    categories: [
      {
        id: 1,
        title: "Healthy Eating",
        tags: ["balanced diet", "meal patterns", "recipes", "immunity boost", "ayurveda"],
        icon: "Leaf",
        recommendedQuestions: ["Working life me balanced diet kaise banaye?", "Immunity ke liye best ghar ka khana kya hai?", "3 meals ya 5 small meals better?"],
      },
      {
        id: 2,
        title: "Special Diets",
        tags: ["vegan", "keto", "diabetic", "low-carb", "gluten-free"],
        icon: "Utensils",
        recommendedQuestions: ["Vegan diet me protein kaise complete kare?", "Keto diet India me safe hai kya?", "Diabetic log roti khaye ya rice?"],
      },
      {
        id: 3,
        title: "Deficiencies & Supplements",
        tags: ["vitamins", "minerals", "protein", "iron", "calcium"],
        icon: "Pill",
        recommendedQuestions: ["Vitamin D deficiency ke symptoms?", "Iron deficiency bina tablets kaise cure kare?", "Protein powder daily lena safe?"],
      },
      {
        id: 4,
        title: "Weight & Body Goals",
        tags: ["weight loss", "muscle gain", "maintenance"],
        icon: "Scale",
        recommendedQuestions: ["Healthy weight loss bina weakness kaise?", "Belly fat kam karne ka best tareeqa?", "Fast metabolism me weight kaise badhaye?"],
      },
      {
        id: 5,
        title: "Medical Nutrition",
        tags: ["diabetes", "hypertension", "kidney issues", "liver issues"],
        icon: "Hospital",
        recommendedQuestions: ["Diabetes ke liye best Indian diet?", "Fatty liver me kya avoid kare?", "Thyroid me kaunse foods helpful?"],
      },
    ],
  },
  fitness: {
    id: 2,
    name: "Fitness",
    icon: "Dumbbell",
    gradient: ["#F9A8D4", "#EC4899"],
    isPopular: false,
    bgColor: "#FCE7F3",
    color: "#DB2777",
    categories: [
      {
        id: 1,
        title: "Exercise & Training",
        tags: ["strength", "cardio", "calisthenics", "home workout", "gym routines"],
        icon: "Dumbbell",
        recommendedQuestions: ["Home workout se result milta hai?", "Beginners ke liye best routine?", "Cardio ya strength pehle kya?"],
      },
      {
        id: 2,
        title: "Mind-Body Practices",
        tags: ["yoga", "pilates", "meditation-based movement", "breathing exercises"],
        icon: "Flower2",
        recommendedQuestions: ["Yoga se weight loss hota hai?", "Breathing exercises anxiety me useful?", "Meditation beginners kaise start kare?"],
      },
      {
        id: 3,
        title: "Sports & Group Fitness",
        tags: ["zumba", "salsa", "aerobics", "team sports", "fun activities"],
        icon: "Trophy",
        recommendedQuestions: ["Zumba se kitni calories burn hoti?", "Team sports fitness ke liye better?", "Group workouts consistency kaise badhate?"],
      },
      {
        id: 4,
        title: "Lifestyle Habits",
        tags: ["posture", "hydration", "sleep", "screen-time balance", "daily activity"],
        icon: "HeartPulse",
        recommendedQuestions: ["Galat posture se back pain kyu?", "Din me kitna paani peena chahiye?", "Daily steps ideal kitne?"],
      },
      {
        id: 5,
        title: "Physio & Recovery",
        tags: ["rehabilitation", "mobility", "flexibility", "injury care"],
        icon: "HandHelping",
        recommendedQuestions: ["Muscle pain ke baad workout safe?", "Knee pain me exercise ya rest?", "Stretching workout se pehle ya baad?"],
      },
    ],
  },
  mental: {
    id: 3,
    name: "Mental Health",
    icon: "Brain",
    gradient: ["#A5B4FC", "#6366F1"],
    isPopular: true,
    bgColor: "#EDE9FE",
    color: "#7C3AED",
    categories: [
      {
        id: 1,
        title: "Stress",
        tags: ["work pressure", "study pressure", "financial stress", "relationship stress", "life changes"],
        icon: "Meh",
        recommendedQuestions: ["Office stress ghar pe kaise kam kare?", "Financial stress neend kyu bigadta hai?", "Stress bina medicine kaise control kare?"],
      },
      {
        id: 2,
        title: "Physical Tension",
        tags: ["headache", "migraines", "eye strain", "neck pain", "shoulder pain"],
        icon: "User",
        recommendedQuestions: ["Daily headache ke reasons kya?", "Screen time se eye strain ka solution?", "Neck–shoulder pain ke home remedies?"],
      },
      {
        id: 3,
        title: "Sleep Issues",
        tags: ["trouble falling asleep", "restless nights", "oversleeping"],
        icon: "Moon",
        recommendedQuestions: ["Neend late aati ho to kya kare?", "Raat ko baar-baar neend kyu khulti hai?", "Zyada sone se bhi thakaan kyu?"],
      },
      {
        id: 4,
        title: "Anxiety & Worry",
        tags: ["constant worrying", "overthinking", "panic", "social fears"],
        icon: "AlertCircle",
        recommendedQuestions: ["Overthinking ka cycle kaise break kare?", "Panic attack aaye to turant kya kare?", "Anxiety aur stress me difference?"],
      },
      {
        id: 5,
        title: "Tension & Depression",
        tags: ["low mood", "hopelessness", "irritability", "loss of motivation"],
        icon: "CloudRain",
        recommendedQuestions: ["Sad feel hota hai roz, normal hai?", "Motivation bilkul nahi hai, kya kare?", "Depression aur sadness me fark?"],
      },
    ],
  },
  general: {
    id: 4,
    name: "General Medicine",
    icon: "Stethoscope",
    gradient: ["#A5F3FC", "#06B6D4"],
    isPopular: true,
    bgColor: "#CCFBF1",
    color: "#0D9488",
    categories: [
      {
        id: 1,
        title: "ENT & Respiratory",
        tags: ["cough", "cold", "sinus", "throat issues", "asthma", "bronchitis", "fever"],
        icon: "Wind",
        recommendedQuestions: ["Baar-baar sardi-khansi kyu hoti hai?", "Sinus headache ka solution kya?", "Throat pain bina fever ke kyu?"],
      },
      {
        id: 2,
        title: "Digestive Health",
        tags: ["indigestion", "constipation", "acidity", "diarrhea", "food poisoning", "jaundice"],
        icon: "Activity",
        recommendedQuestions: ["Roz acidity kyu hoti hai?", "Constipation ka natural solution?", "Gas aur bloating ke reasons?"],
      },
      {
        id: 3,
        title: "Bone & Joint (Ortho)",
        tags: ["back pain", "arthritis", "fractures", "sprains", "neck strain", "muscle strain"],
        icon: "Bone",
        recommendedQuestions: ["Lower back pain ke causes?", "Arthritis young age me kyu?", "Calcium bina tablets kaise mile?"],
      },
      {
        id: 4,
        title: "Eye Care",
        tags: ["vision problems", "redness", "irritation", "eye checkups", "corrective surgery"],
        icon: "Eye",
        recommendedQuestions: ["Aankhon me redness roz kyu?", "Blue light se eyes kaise bache?", "Eye checkup kitne time me?"],
      },
      {
        id: 5,
        title: "Oral & Dental",
        tags: ["toothache", "cavities", "gum issues", "mouth ulcers", "dental hygiene"],
        icon: "Smile",
        recommendedQuestions: ["Toothache raat ko zyada kyu?", "Bleeding gums ka reason?", "Scaling se teeth weak hoti?"],
      },
      {
        id: 6,
        title: "Child Care",
        tags: ["infant nutrition", "vaccination", "common infections", "parenting", "adolescence"],
        icon: "Baby",
        recommendedQuestions: ["Infant ko solid food kab?", "Bacche baar-baar bimar kyu?", "Screen time bacchon ke liye safe?"],
      },
      {
        id: 7,
        title: "Pet Health",
        tags: ["dog", "cat", "fish", "bird", "cattle"],
        icon: "PawPrint",
        recommendedQuestions: ["Dog khana kam kyu khata hai?", "Cat vaccination ka gap kitna?", "Fish tank me fish kyu marti?"],
      },
    ],
  },
  sexual: {
    id: 5,
    name: "Sexual Health",
    icon: "Heart",
    gradient: ["#FCA5A5", "#EF4444"],
    isPopular: false,
    bgColor: "#FFEDD5",
    color: "#EA580C",
    categories: [
      {
        id: 1,
        title: "Performance Issues",
        tags: ["erectile dysfunction", "premature ejaculation", "low libido", "performance anxiety"],
        icon: "Zap",
        recommendedQuestions: ["Performance anxiety kaise door kare?", "ED stress se hota hai?", "Premature ejaculation ka solution?"],
      },
      {
        id: 2,
        title: "Reproductive Health",
        tags: ["fertility", "contraception", "family planning", "pregnancy-related care"],
        icon: "Baby",
        recommendedQuestions: ["Fertility test kab karwana chahiye?", "Safe contraception ka best option?", "IVF kab consider kare?"],
      },
      {
        id: 3,
        title: "Female Sexual Health",
        tags: ["menopause", "PCOS", "gynecological checkups", "menstrual wellness"],
        icon: "User",
        recommendedQuestions: ["PCOS me periods irregular kyu?", "Painful periods normal?", "Menopause symptoms kaise manage kare?"],
      },
      {
        id: 4,
        title: "Hygiene & Safety",
        tags: ["STDs", "UTIs", "infections", "safe practices", "hygiene"],
        icon: "ShieldCheck",
        recommendedQuestions: ["UTI baar-baar kyu hota hai?", "STD ke early symptoms?", "Unsafe sex ke baad kya kare?"],
      },
      {
        id: 5,
        title: "Psychological & Intimacy",
        tags: ["intimacy concerns", "relationship stress", "sexual confidence"],
        icon: "Heart",
        recommendedQuestions: ["Intimacy me awkwardness kyu?", "Relationship stress sex life pe effect?", "Body image issues confidence kaise girate?"],
      },
      {
        id: 6,
        title: "Counseling & Education",
        tags: ["sexual literacy", "consent", "healthy relationships", "guidance"],
        icon: "BookOpen",
        recommendedQuestions: ["Sexual education kyu important?", "Consent ka real meaning kya?", "Porn expectations reality ko kaise distort karti?"],
      },
    ],
  },
  chronic: {
    id: 6,
    name: "Chronic Diseases",
    icon: "Activity",
    gradient: ["#aa97f4ff", "#8B5CF6"],
    isPopular: false,
    bgColor: "#EDE9FE",
    color: "#7C3AED",
    categories: [
      {
        id: 1,
        title: "Heart & Blood Pressure",
        tags: ["hypertension", "heart disease", "chest pain"],
        icon: "HeartPulse",
        recommendedQuestions: ["BP normal hone par bhi medicine zaroori?", "High BP me exercise safe?", "Heart attack ke warning signs?"],
      },
      {
        id: 2,
        title: "Diabetes & Metabolism",
        tags: ["blood sugar control", "insulin", "metabolic health"],
        icon: "Droplet",
        recommendedQuestions: ["Sugar normal hone par bhi diabetes kyu?", "Fruits diabetes me safe?", "Insulin kab start hoti?"],
      },
      {
        id: 3,
        title: "Kidney Health",
        tags: ["chronic kidney disease", "kidney stones", "renal monitoring"],
        icon: "Droplet",
        recommendedQuestions: ["Kidney stone dubara kyu banta?", "Creatinine badhne ka matlab?", "Kidney patient ko protein safe?"],
      },
      {
        id: 4,
        title: "Respiratory Health",
        tags: ["asthma", "COPD", "long-term breathing problems"],
        icon: "Wind",
        recommendedQuestions: ["Asthma attack sudden kyu?", "Inhaler aadat bana deta?", "Long-term cough kab serious?"],
      },
      {
        id: 5,
        title: "Cancer Care",
        tags: ["breast", "lung", "prostate", "intestinal", "skin", "blood cancers"],
        icon: "Ribbon",
        recommendedQuestions: ["Cancer early stage me kaise detect?", "Family history se risk kitna?", "Treatment ke baad normal life possible?"],
      },
      {
        id: 6,
        title: "Emergency Care",
        tags: ["heart attack", "stroke", "choking", "burns", "allergies", "poisoning", "fainting", "paralysis"],
        icon: "BriefcaseMedical",
        recommendedQuestions: ["Heart attack me pehle 10 min kya kare?", "Stroke ke early symptoms?", "Choking ho jaye to kya kare?"],
      },
    ],
  },
  skin: {
    id: 7,
    name: "Skin & Beauty",
    icon: "Sparkles",
    gradient: ["#F472B6", "#DB2777"],
    isPopular: false,
    bgColor: "#FCE7F3",
    color: "#DB2777",
    categories: [
      {
        id: 1,
        title: "Acne & Blemishes",
        tags: ["pimples", "blackheads", "scars", "oily skin"],
        icon: "User",
        recommendedQuestions: ["Pimples baar-baar kyu aate hain?", "Acne scars kaise fade kare?", "Oily skin ka permanent solution?"],
      },
      {
        id: 2,
        title: "Dryness & Sensitivity",
        tags: ["dry skin", "eczema", "irritation", "allergies"],
        icon: "Droplet",
        recommendedQuestions: ["Dry skin ke liye best moisturizer?", "Skin sensitivity ka karan kya hai?", "Winter me skin kaise protect kare?"],
      },
      {
        id: 3,
        title: "Pigmentation & Tone",
        tags: ["uneven tone", "dark spots", "tanning", "melasma"],
        icon: "Palette",
        recommendedQuestions: ["Dark spots kaise hataye?", "Uneven skin tone ka reason?", "Tanning se kaise bache?"],
      },
      {
        id: 4,
        title: "Anti-Aging & Renewal",
        tags: ["wrinkles", "fine lines", "collagen", "firmness"],
        icon: "Sparkles",
        recommendedQuestions: ["Wrinkles kam karne ka natural tarika?", "Anti-aging skincare kab start kare?", "Collagen naturally kaise badhaye?"],
      },
      {
        id: 5,
        title: "Infections & Rashes",
        tags: ["fungal infection", "rashes", "itching", "redness"],
        icon: "Bandage",
        recommendedQuestions: ["Fungal infection kaise pehchane?", "Itching ka immediate relief?", "Rashes repeat kyu hoti hain?"],
      },
      {
        id: 6,
        title: "Hair & Scalp Care",
        tags: ["dandruff", "hair fall", "itchy scalp", "oily scalp"],
        icon: "Scissors",
        recommendedQuestions: ["Dandruff ka permanent solution?", "Hair fall ruk nahi raha, kya kare?", "Oily scalp ke liye best shampoo?"],
      },
    ],
  },
  addiction: {
    id: 8,
    name: "Addiction",
    icon: "Ban",
    gradient: ["#FB923C", "#EA580C"],
    isPopular: true,
    bgColor: "#FEE2E2",
    color: "#DC2626",
    categories: [
      {
        id: 1,
        title: "Substance Addiction",
        tags: ["alcohol", "drugs", "nicotine", "prescription misuse"],
        icon: "Pill",
        recommendedQuestions: ["Social drinking kab addiction ban jaati hai?", "Smoking kam karna bhi faydemand hota hai?", "Ganja habit hai ya addiction?"],
      },
      {
        id: 2,
        title: "Digital Addiction",
        tags: ["phone", "social media", "gaming", "internet"],
        icon: "Smartphone",
        recommendedQuestions: ["Phone addiction kaise pehchane?", "Reels dekhte waqt time ka pata kyu nahi chalta?", "Digital detox realistically kaise kare?"],
      },
      {
        id: 3,
        title: "Food & Sugar Addiction",
        tags: ["binge eating", "junk food", "sugar cravings"],
        icon: "Pizza",
        recommendedQuestions: ["Sugar cravings kaise control kare?", "Binge eating kyu hoti hai?", "Emotional eating se kaise bache?"],
      },
      {
        id: 4,
        title: "Work & Productivity Addiction",
        tags: ["workaholism", "burnout", "overworking"],
        icon: "Briefcase",
        recommendedQuestions: ["Workaholism ka sign kya hai?", "Burnout se kaise recover kare?", "Work-life balance kaise banaye?"],
      },
      {
        id: 5,
        title: "Recovery & Relapse Support",
        tags: ["withdrawal", "support systems", "healing", "motivation"],
        icon: "Heart",
        recommendedQuestions: ["Relapse ke baad vapas kaise start kare?", "Recovery me motivation kaise banaye rakhe?", "Support group kaise join kare?"],
      },
    ],
  },
  finance: {
    id: 9,
    name: "Finance",
    icon: "Coins",
    gradient: ["#6EE7B7", "#10B981"],
    isPopular: false,
    bgColor: "#D1FAE5",
    color: "#059669",
    categories: [
      {
        id: 1,
        title: "Budgeting & Saving",
        tags: ["personal finance", "budget planning", "saving goals", "spending control"],
        icon: "Wallet",
        recommendedQuestions: ["Monthly budget kaise banaye?", "Savings ka target kaise set kare?", "Unnecessary expenses kaise avoid kare?"],
      },
      {
        id: 2,
        title: "Investments",
        tags: ["mutual funds", "stocks", "bonds", "gold", "real estate"],
        icon: "TrendingUp",
        recommendedQuestions: ["Mutual fund FD se better kab hota hai?", "SIP kis income pe start karni chahiye?", "Market girne par investment band kare ya continue?"],
      },
      {
        id: 3,
        title: "Insurance Planning",
        tags: ["health insurance", "life insurance", "vehicle insurance"],
        icon: "ShieldCheck",
        recommendedQuestions: ["Health insurance kab lena best hota hai?", "Term insurance aur ULIP me difference?", "Insurance cover kitna hona chahiye?"],
      },
      {
        id: 4,
        title: "Loans & Credit",
        tags: ["home loan", "education loan", "credit score", "EMI management"],
        icon: "CreditCard",
        recommendedQuestions: ["Home loan EMI safe limit kitni hoti hai?", "Credit card limit badhwana safe hota hai?", "Credit card se credit score kaise improve kare?"],
      },
      {
        id: 5,
        title: "Tax & Compliance",
        tags: ["income tax", "returns", "deductions", "filing"],
        icon: "FileText",
        recommendedQuestions: ["ITR filing kab compulsory hai?", "Tax saving ke simple tareeke?", "Tax deductions kaunse claim kar sakte hain?"],
      },
    ],
  },
  tax: {
    id: 10,
    name: "CA Taxes",
    icon: "Calculator",
    gradient: ["#34D399", "#059669"],
    isPopular: false,
    bgColor: "#D1FAE5",
    color: "#059669",
    categories: [
      {
        id: 1,
        title: "Income Tax",
        tags: ["returns", "TDS", "advance tax", "exemptions"],
        icon: "FileText",
        recommendedQuestions: ["Income tax return kaise file kare?", "TDS refund kaise claim kare?", "Tax exemption limit kya hai?"],
      },
      {
        id: 2,
        title: "GST & Indirect Taxes",
        tags: ["GST filing", "input credit", "rates", "e-invoice"],
        icon: "Receipt",
        recommendedQuestions: ["GST return late hone par penalty?", "Input tax credit kab reject hota hai?", "E-invoice kis par mandatory hota hai?"],
      },
      {
        id: 3,
        title: "Audit & Accounting",
        tags: ["bookkeeping", "financial statements", "audit reports"],
        icon: "ClipboardList",
        recommendedQuestions: ["Audit kyu hota hai?", "Basic accounting kaise sikhe?", "Financial statements kaise padhe?"],
      },
      {
        id: 4,
        title: "Business Compliance",
        tags: ["startup registration", "licenses", "certifications", "ROC filing"],
        icon: "Briefcase",
        recommendedQuestions: ["Company incorporation ka process kya hota hai?", "Startup India certificate ka kya fayda?", "Annual compliance miss ho jaye to kya hota hai?"],
      },
      {
        id: 5,
        title: "Tax Planning & Optimization",
        tags: ["deductions", "rebates", "financial planning", "savings"],
        icon: "TrendingUp",
        recommendedQuestions: ["Legal tax saving ke best tareeke kaunse hain?", "Advance tax kab bharna hota hai?", "Cash transaction ki legal limit kya hai?"],
      },
    ],
  },
  lawyer: {
    id: 11,
    name: "Lawyer",
    icon: "Scale",
    gradient: ["#93C5FD", "#3B82F6"],
    isPopular: false,
    bgColor: "#BFDBFE",
    color: "#2563EB",
    categories: [
      {
        id: 1,
        title: "Legal Advice & Consultation",
        tags: ["legal help", "rights", "law queries", "case guidance"],
        icon: "UserCheck",
        recommendedQuestions: ["Legal notice ka matlab kya hai?", "Apne rights kaise protect kare?", "Lawyer kab hire karna chahiye?"],
      },
      {
        id: 2,
        title: "Contracts & Agreements",
        tags: ["rental agreements", "business contracts", "NDAs", "partnership deeds"],
        icon: "FileText",
        recommendedQuestions: ["Contract sign karne se pehle kya check kare?", "Agreement breach hone par kya kare?", "Rental agreement ke important clauses?"],
      },
      {
        id: 3,
        title: "Family & Marriage Law",
        tags: ["divorce", "alimony", "child custody", "domestic rights"],
        icon: "Home",
        recommendedQuestions: ["Divorce me settlement kaise hota hai?", "Child custody ka decision kaise hota hai?", "Domestic dispute me legal options kya hain?"],
      },
      {
        id: 4,
        title: "Criminal & Civil Matters",
        tags: ["FIR", "bail", "consumer rights", "disputes"],
        icon: "Gavel",
        recommendedQuestions: ["FIR online kaise file kare?", "Traffic challan galat aaye to kya kare?", "Refund deny ho to legal step kya hai?"],
      },
      {
        id: 5,
        title: "Corporate & Startup Law",
        tags: ["company formation", "compliance", "intellectual property", "labor laws"],
        icon: "Building",
        recommendedQuestions: ["Startup ke liye legal structure kaunsa best?", "Intellectual property kaise protect kare?", "Co-founder agreement me kya include kare?"],
      },
      {
        id: 6,
        title: "Property & Real Estate Law",
        tags: ["land disputes", "registration", "leases", "property transfer"],
        icon: "MapPin",
        recommendedQuestions: ["Property dispute kaise avoid kare?", "Registry aur agreement me difference?", "Property fraud kaise pehchane?"],
      },
    ],
  },
  government: {
    id: 12,
    name: "Government",
    icon: "Landmark",
    gradient: ["#60A5FA", "#2563EB"],
    isPopular: false,
    bgColor: "#DBEAFE",
    color: "#2563EB",
    categories: [
      {
        id: 1,
        title: "Documents & IDs",
        tags: ["Aadhaar", "PAN", "passport", "voter ID", "driving license"],
        icon: "IdCard",
        recommendedQuestions: ["Aadhaar update me kitna time lagta hai?", "PAN–Aadhaar link miss ho jaye to?", "Birth certificate error kaise correct kare?"],
      },
      {
        id: 2,
        title: "Government Schemes",
        tags: ["PMAY", "PM Kisan", "pensions", "education aid", "loans"],
        icon: "Hand",
        recommendedQuestions: ["Eligible scheme kaise identify kare?", "Subsidy milne me delay kyu hota hai?", "Scholarship reject hone ke reasons?"],
      },
      {
        id: 3,
        title: "Public Grievances & Rights",
        tags: ["RTI", "consumer complaints", "citizen rights", "ombudsman"],
        icon: "Megaphone",
        recommendedQuestions: ["RTI ka reply na aaye to kya kare?", "Noise pollution complaint kaha kare?", "Cyber crime report kaise kare?"],
      },
      {
        id: 4,
        title: "Education & Employment Services",
        tags: ["scholarships", "skill development", "government jobs"],
        icon: "School",
        recommendedQuestions: ["Government scholarship kaise apply kare?", "Sarkari naukri ke liye best preparation?", "Skill development schemes konsi hain?"],
      },
      {
        id: 5,
        title: "Business & Licenses",
        tags: ["MSME", "GST registration", "startup India", "trade license"],
        icon: "Building",
        recommendedQuestions: ["Business registration kaise kare?", "Trade license lene ka process?", "MSME certificate ke benefits?"],
      },
      {
        id: 6,
        title: "Citizen Welfare & Safety",
        tags: ["women helpline", "senior citizen care", "public safety", "emergency contacts"],
        icon: "Shield",
        recommendedQuestions: ["Women helpline number kya hai?", "Emergency me kisko contact kare?", "Senior citizen welfare schemes?"],
      },
    ],
  },
  career: {
    id: 13,
    name: "Career Coach",
    icon: "Briefcase",
    gradient: ["#FCD34D", "#F59E0B"],
    isPopular: true,
    bgColor: "#FFEDD5",
    color: "#EA580C",
    categories: [
      {
        id: 1,
        title: "Education",
        tags: ["school", "college", "skill development", "vocational courses", "admissions", "scholarships"],
        icon: "BookOpen",
        recommendedQuestions: ["12th ke baad best course konsa?", "Scholarship kaise apply kare?", "Online courses worth hai kya?"],
      },
      {
        id: 2,
        title: "Employment",
        tags: ["jobs", "government vacancies", "internships", "career guidance", "professional growth"],
        icon: "Briefcase",
        recommendedQuestions: ["Job change ka sahi time kaise pehchane?", "Resume short rakhe ya detailed?", "Interview me gap year kaise explain kare?"],
      },
      {
        id: 3,
        title: "Business & Entrepreneurship",
        tags: ["startups", "MSME", "manufacturing", "agriculture", "tenders", "GEM"],
        icon: "Lightbulb",
        recommendedQuestions: ["Startup kaise shuru kare?", "Business idea validate kaise kare?", "Funding kaha se mile?"],
      },
      {
        id: 4,
        title: "Self-Employed",
        tags: ["freelancing", "consultants", "micro-businesses", "local services", "home-based businesses", "professionals"],
        icon: "UserCheck",
        recommendedQuestions: ["Freelancing me clients kaise dhunde?", "Pricing kitni rakhni chahiye?", "Clients se payment time pe kaise le?"],
      },
    ],
  },
  shopping: {
    id: 14,
    name: "Shopping",
    icon: "ShoppingBag",
    gradient: ["#998bd3ff", "#8B5CF6"],
    isPopular: false,
    bgColor: "#EDE9FE",
    color: "#7C3AED",
    categories: [
      {
        id: 1,
        title: "Gadgets",
        tags: ["electronics", "mobiles", "laptops", "tablets", "smartwatches", "accessories"],
        icon: "Smartphone",
        recommendedQuestions: ["Phone me camera ya processor kya choose kare?", "Refurbished gadgets safe hote hain kya?", "Fake reviews kaise identify kare?"],
      },
      {
        id: 2,
        title: "Furniture",
        tags: ["home", "office", "decor", "storage", "outdoor", "modular solutions"],
        icon: "Armchair",
        recommendedQuestions: ["Furniture quality kaise check kare?", "Small space ke liye best furniture?", "Solid wood vs engineered wood?"],
      },
      {
        id: 3,
        title: "Apparel",
        tags: ["men", "women", "kids", "ethnic", "sportswear", "accessories"],
        icon: "ShoppingBag",
        recommendedQuestions: ["Online shopping me size kaise choose kare?", "Budget me fashionable kaise rahe?", "Fabric quality kaise pehchane?"],
      },
      {
        id: 4,
        title: "Automotive",
        tags: ["cars", "bikes", "scooters", "spare parts", "accessories", "EVs"],
        icon: "Car",
        recommendedQuestions: ["Petrol vs diesel vs EV kaise decide kare?", "Used car lete waqt kya check kare?", "Service centre overcharge kaise pehchane?"],
      },
      {
        id: 5,
        title: "Home & Kitchen",
        tags: ["appliances", "cookware", "furniture", "lighting", "storage"],
        icon: "Home",
        recommendedQuestions: ["Kitchen appliances me kya invest kare?", "Energy-efficient products kaise pehchane?", "Cookware safe aur durable kaunsa?"],
      },
    ],
  },
  relationship: {
    id: 15,
    name: "Relationship",
    icon: "Users",
    gradient: ["#F9A8D4", "#EC4899"],
    isPopular: false,
    bgColor: "#FCE7F3",
    color: "#DB2777",
    categories: [
      {
        id: 1,
        title: "Dating & Attraction",
        tags: ["flirting", "first dates", "chemistry", "building connection", "online dating"],
        icon: "Heart",
        recommendedQuestions: ["Dating apps ke red flags kya hote hain?", "Compatibility early stage me kaise judge kare?", "Ghosting ka matlab kya hota hai?"],
      },
      {
        id: 2,
        title: "Marriage & Commitment",
        tags: ["long-term relationships", "trust", "compatibility", "intimacy", "partnership goals"],
        icon: "Circle",
        recommendedQuestions: ["Arranged vs love marriage ke challenges?", "Shaadi ke baad expectation mismatch ka solution?", "Marriage counseling kab leni chahiye?"],
      },
      {
        id: 3,
        title: "Communication & Conflict",
        tags: ["arguments", "boundaries", "emotional expression", "listening", "healing fights"],
        icon: "MessageCircle",
        recommendedQuestions: ["Partner se effectively kaise baat kare?", "Arguments avoid kaise kare?", "Boundaries kaise set kare relationship me?"],
      },
      {
        id: 4,
        title: "Family & Parenting",
        tags: ["family dynamics", "in-laws", "children", "co-parenting", "work-life balance"],
        icon: "Home",
        recommendedQuestions: ["Discipline aur freedom ka balance kaise rakhe?", "Bacchon ka confidence kaise build kare?", "Teen mood swings normal hote hain?"],
      },
      {
        id: 5,
        title: "Breakups & Healing",
        tags: ["moving on", "self-worth", "letting go", "recovery", "closure", "self-love"],
        icon: "HeartOff",
        recommendedQuestions: ["Breakup ke baad move on kaise kare?", "Self-love kaise develop kare?", "Ex ko bhoolne ka tarika?"],
      },
    ],
  },
  astro: {
    id: 16,
    name: "Astro",
    icon: "Moon",
    gradient: ["#A78BFA", "#7C3AED"],
    isPopular: false,
    bgColor: "#EDE9FE",
    color: "#7C3AED",
    categories: [
      {
        id: 1,
        title: "Zodiac Insights",
        tags: ["sun signs", "moon signs", "rising signs", "horoscope", "daily predictions"],
        icon: "Star",
        recommendedQuestions: ["Daily horoscope kitna reliable hota hai?", "Career prediction kaise padhe?", "Negative horoscope ka fear kaise handle kare?"],
      },
      {
        id: 2,
        title: "Love & Compatibility",
        tags: ["relationship matches", "emotional chemistry", "communication styles", "trust and attraction"],
        icon: "Heart",
        recommendedQuestions: ["Kundli matching kitni important hoti hai?", "Astrology se relationship success predict hota hai?", "Manglik dosh ka real impact?"],
      },
      {
        id: 3,
        title: "Career & Growth",
        tags: ["career path", "success timing", "planetary support", "decision guidance"],
        icon: "Briefcase",
        recommendedQuestions: ["Career change ka sahi time kab hai?", "Job me success ke liye planetary support?", "Business start karne ka best time?"],
      },
      {
        id: 4,
        title: "Health & Energy",
        tags: ["mind-body balance", "spiritual healing", "planetary influence on health", "well-being cycles"],
        icon: "Activity",
        recommendedQuestions: ["Planetary positions health ko kaise affect karte?", "Energy levels kaise balance kare?", "Meditation ka best time kya hai?"],
      },
      {
        id: 5,
        title: "Life Path & Karma",
        tags: ["birth chart insights", "soul purpose", "past karma", "spiritual evolution"],
        icon: "Infinity",
        recommendedQuestions: ["Birth chart se life purpose kaise jane?", "Karma ka effect kaise samjhe?", "Spiritual growth me astrology ka role?"],
      },
    ],
  },
};

