export interface AdvisorCategory {
  id: number;
  name: string;
  icon: string;
  gradient: string[];
  isPopular: boolean;
  bgColor: string;
  color: string;
  categories: {
    id: number;
    title: string;
    tags: string[];
    icon: string;
    recommendedQuestions: string[];
  }[];
}

export const ADVISOR_CATEGORIES: Record<string, AdvisorCategory> = {
  nutrition: {
    id: 1,
    name: "Nutrition & Diet",
    icon: "Salad",
    gradient: ["#6EE7B7", "#10B981"],
    isPopular: true,
    bgColor: "#CCFBF1",
    color: "#0D9488",
    categories: [
      {
        id: 1,
        title: "Healthy Eating",
        tags: ["balanced diet", "meal patterns", "recipes", "immunity boost", "ayurveda"],
        icon: "Leaf",
        recommendedQuestions: [
          "Healthy eating with busy jobs?",
          "Simple foods for immunity?",
          "Three meals or frequent snacks?",
          "How to meal prep efficiently?",
        ],  
      },
      {
        id: 2,
        title: "Special Diets",
        tags: ["vegan", "keto", "diabetic", "low-carb", "gluten-free"],
        icon: "Utensils",
        recommendedQuestions: [
          "Protein sources on vegan diet?",
          "Is keto safe long term?",
          "Rice or bread for diabetes?",
          "How to transition to a new diet?",
        ],  
      },
      {
        id: 3,
        title: "Deficiencies & Supplements",
        tags: ["vitamins", "minerals", "protein", "iron", "calcium"],
        icon: "Pill",
        recommendedQuestions: ["Signs of vitamin D deficiency?", "Natural ways to raise iron?", "Is daily whey protein safe?", "How long to see supplement benefits?"],
      },
      {
        id: 4,
        title: "Weight & Body Goals",
        tags: ["weight loss", "muscle gain", "maintenance"],
        icon: "Scale",
        recommendedQuestions: ["Safe weight loss without fatigue?", "Best ways to reduce belly fat?", "Gaining weight with fast metabolism?", "How to track progress beyond weight?"],
      },
      {
        id: 5,
        title: "Medical Nutrition",
        tags: ["diabetes", "hypertension", "kidney issues", "liver issues"],
        icon: "Hospital",
        recommendedQuestions: ["Best diet for type-2 diabetes?", "Foods worsening fatty liver disease?", "Foods supporting thyroid health?", "Can diet reverse health conditions?"],
      },
    ],
  },
  fitness: {
    id: 2,
    name: "Fitness",
    icon: "Dumbbell",
    gradient: ["#F9A8D4", "#EC4899"],
    isPopular: false,
    bgColor: "#FCE7F3",
    color: "#DB2777",
    categories: [
      {
        id: 1,
        title: "Exercise & Training",
        tags: ["strength", "cardio", "calisthenics", "home workout", "gym routines"],
        icon: "Dumbbell",
        recommendedQuestions: ["Do home workouts actually work?", "Best workout plan for beginners?", "Cardio or strength training first?", "How to stay consistent with workouts?"],
      },
      {
        id: 2,
        title: "Mind-Body Practices",
        tags: ["yoga", "pilates", "meditation-based movement", "breathing exercises"],
        icon: "Flower2",
        recommendedQuestions: ["Yoga effective for weight loss?", "Breathing exercises reduce anxiety?", "Easy ways to start meditation?", "How long before seeing mind-body benefits?"],
      },
      {
        id: 3,
        title: "Sports & Group Fitness",
        tags: ["zumba", "salsa", "aerobics", "team sports", "fun activities"],
        icon: "Trophy",
        recommendedQuestions: ["Dance workouts good for fat loss?", "Team sports improve overall fitness?", "Group workouts improve consistency?", "How to choose the right sport for you?"],
      },
      {
        id: 4,
        title: "Lifestyle Habits",
        tags: ["posture", "hydration", "sleep", "screen-time balance", "daily activity"],
        icon: "HeartPulse",
        recommendedQuestions: ["Poor posture causing back pain?", "Recommended daily water intake?", "Ideal daily step count?", "How to build healthy daily habits?"],
      },
      {
        id: 5,
        title: "Physio & Recovery",
        tags: ["rehabilitation", "mobility", "flexibility", "injury care"],
        icon: "HandHelping",
        recommendedQuestions: ["Exercise with sore muscles safe?", "Knee pain—rest or movement?", "Stretch before or after workouts?", "How to prevent workout injuries?"],
      },
    ],
  },
  mental: {
    id: 3,
    name: "Mental Health",
    icon: "Brain",
    gradient: ["#A5B4FC", "#6366F1"],
    isPopular: true,
    bgColor: "#EDE9FE",
    color: "#7C3AED",
    categories: [
      {
        id: 1,
        title: "Stress",
        tags: ["work pressure", "study pressure", "financial stress", "relationship stress", "life changes"],
        icon: "Meh",
        recommendedQuestions: ["How to relax after work?", "Why stress disrupts sleep cycles?", "Natural ways to manage stress?", "When is stress a sign of something serious?"],
      },
      {
        id: 2,
        title: "Physical Tension",
        tags: ["headache", "migraines", "eye strain", "neck pain", "shoulder pain"],
        icon: "User",
        recommendedQuestions: ["Causes of frequent headaches?", "Screen-related eye strain solutions?", "Home relief for neck pain?", "How to prevent tension-related pain?"],
      },
      {
        id: 3,
        title: "Sleep Issues",
        tags: ["trouble falling asleep", "restless nights", "oversleeping"],
        icon: "Moon",
        recommendedQuestions: ["Trouble falling asleep every night?", "Why sleep breaks during night?", "Oversleeping but still feeling tired?", "How to improve sleep quality naturally?"],
      },
      {
        id: 4,
        title: "Anxiety & Worry",
        tags: ["constant worrying", "overthinking", "panic", "social fears"],
        icon: "AlertCircle",
        recommendedQuestions: ["How to stop overthinking habits?", "Immediate panic attack relief methods?", "Anxiety versus stress difference?", "When should I seek professional help?"],
      },
      {
        id: 5,
        title: "Tension & Depression",
        tags: ["low mood", "hopelessness", "irritability", "loss of motivation"],
        icon: "CloudRain",
        recommendedQuestions: ["When low mood becomes depression?", "Sudden irritability without clear reason?", "No motivation—what actually helps?", "Can lifestyle changes ease depression?"],
      },
    ],
  },
  general: {
    id: 4,
    name: "General Medicine",
    icon: "Stethoscope",
    gradient: ["#A5F3FC", "#06B6D4"],
    isPopular: true,
    bgColor: "#CCFBF1",
    color: "#0D9488",
    categories: [
      {
        id: 1,
        title: "ENT & Respiratory",
        tags: ["cough", "cold", "sinus", "throat issues", "asthma", "bronchitis", "fever"],
        icon: "Wind",
        recommendedQuestions: ["Why frequent colds occur?", "Managing chronic sinus headaches?", "Throat pain without fever?", "How to boost immunity against colds?"],
      },
      {
        id: 2,
        title: "Digestive Health",
        tags: ["indigestion", "constipation", "acidity", "diarrhea", "food poisoning", "jaundice"],
        icon: "Activity",
        recommendedQuestions: ["Daily acid reflux causes?", "Natural remedies for constipation?", "Causes of gas and bloating?", "How to maintain digestive health long-term?"],
      },
      {
        id: 3,
        title: "Bone & Joint (Ortho)",
        tags: ["back pain", "arthritis", "fractures", "sprains", "neck strain", "muscle strain"],
        icon: "Bone",
        recommendedQuestions: ["Causes of lower back pain?", "Early arthritis—why does it happen?", "Natural ways to strengthen bones?", "What exercises help joint health?"],
      },
      {
        id: 4,
        title: "Eye Care",
        tags: ["vision problems", "redness", "irritation", "eye checkups", "corrective surgery"],
        icon: "Eye",
        recommendedQuestions: ["Frequent red or dry eyes?", "Protecting eyes from blue light?", "Eye exam frequency needed?", "How to rest eyes from screens?"],
      },
      {
        id: 5,
        title: "Oral & Dental",
        tags: ["toothache", "cavities", "gum issues", "mouth ulcers", "dental hygiene"],
        icon: "Smile",
        recommendedQuestions: ["Tooth pain worse at night?", "Causes of bleeding gums?", "Does dental scaling weaken teeth?", "How often should I visit dentist?"],
      },
      {
        id: 6,
        title: "Child Care",
        tags: ["infant nutrition", "vaccination", "common infections", "parenting", "adolescence"],
        icon: "Baby",
        recommendedQuestions: ["When should solid foods start?", "Why do kids get sick often?", "How to boost child immunity naturally?", "What vaccinations are essential?"],
      },
      {
        id: 7,
        title: "Pet Health",
        tags: ["dog", "cat", "fish", "bird", "cattle"],
        icon: "PawPrint",
        recommendedQuestions: ["Sudden vomiting in pets—why?", "Why is my pet lethargic?", "Signs of pain in animals?", "How to keep pets healthy and active?"],
      },
    ],
  },
  sexual: {
    id: 5,
    name: "Sexual Health",
    icon: "Heart",
    gradient: ["#FCA5A5", "#EF4444"],
    isPopular: false,
    bgColor: "#FFEDD5",
    color: "#EA580C",
    categories: [
      {
        id: 1,
        title: "Performance Issues",
        tags: ["erectile dysfunction", "premature ejaculation", "low libido", "performance anxiety"],
        icon: "Zap",
        recommendedQuestions: ["Solutions for premature ejaculation?", "Reducing performance anxiety naturally?", "Can stress cause erectile dysfunction?", "When should I see a specialist?"],
      },
      {
        id: 2,
        title: "Reproductive Health",
        tags: ["fertility", "contraception", "family planning", "pregnancy-related care"],
        icon: "Baby",
        recommendedQuestions: ["When to do fertility testing?", "Safest contraception options available?", "When is IVF recommended?", "How to prepare for pregnancy?"],
      },
      {
        id: 3,
        title: "Female Sexual Health",
        tags: ["menopause", "PCOS", "gynecological checkups", "menstrual wellness"],
        icon: "User",
        recommendedQuestions: ["PCOS causing irregular periods?", "Are painful periods normal?", "Managing menopause symptoms naturally?", "How to track menstrual health?"],
      },
      {
        id: 4,
        title: "Hygiene & Safety",
        tags: ["STDs", "UTIs", "infections", "safe practices", "hygiene"],
        icon: "ShieldCheck",
        recommendedQuestions: ["Why UTIs keep recurring?", "Early signs of STDs?", "Steps after unprotected sex?", "How to maintain intimate hygiene?"],
      },
      {
        id: 5,
        title: "Psychological & Intimacy",
        tags: ["intimacy concerns", "relationship stress", "sexual confidence"],
        icon: "Heart",
        recommendedQuestions: ["Stress impact on sex life?", "Body image affecting intimacy?", "Improving communication with partner?", "How to rebuild intimacy in relationships?"],
      },
      {
        id: 6,
        title: "Counseling & Education",
        tags: ["sexual literacy", "consent", "healthy relationships", "guidance"],
        icon: "BookOpen",
        recommendedQuestions: ["Why is sexual education important?", "What does informed consent mean?", "How to discuss sexual concerns safely?", "Resources for sexual health education?"],
      },
    ],
  },
  chronic: {
    id: 6,
    name: "Chronic Diseases",
    icon: "Activity",
    gradient: ["#aa97f4ff", "#8B5CF6"],
    isPopular: false,
    bgColor: "#EDE9FE",
    color: "#7C3AED",
    categories: [
      {
        id: 1,
        title: "Heart & Blood Pressure",
        tags: ["hypertension", "heart disease", "chest pain"],
        icon: "HeartPulse",
        recommendedQuestions: ["Stop BP medication after control?", "Exercise safe with high blood pressure?", "Heart attack warning signs?", "How to manage heart health daily?"],
      },
      {
        id: 2,
        title: "Diabetes & Metabolism",
        tags: ["blood sugar control", "insulin", "metabolic health"],
        icon: "Droplet",
        recommendedQuestions: ["Why diabetes never fully disappears?", "Are fruits safe for diabetics?", "When is insulin required?", "How to prevent diabetes complications?"],
      },
      {
        id: 3,
        title: "Kidney Health",
        tags: ["chronic kidney disease", "kidney stones", "renal monitoring"],
        icon: "Droplet",
        recommendedQuestions: ["Why kidney stones recur?", "Meaning of high creatinine?", "High-protein diet safe for kidneys?", "How to maintain kidney health?"],
      },
      {
        id: 4,
        title: "Respiratory Health",
        tags: ["asthma", "COPD", "long-term breathing problems"],
        icon: "Wind",
        recommendedQuestions: ["Sudden asthma attacks—why happen?", "Do inhalers cause dependence?", "When is chronic cough serious?", "How to manage asthma long-term?"],
      },
      {
        id: 5,
        title: "Cancer Care",
        tags: ["breast", "lung", "prostate", "intestinal", "skin", "blood cancers"],
        icon: "Ribbon",
        recommendedQuestions: ["What are early cancer warning signs?", "How often are cancer screenings needed?", "Can lifestyle changes reduce cancer risk?", "How to support someone with cancer?"],
      },
      {
        id: 6,
        title: "Emergency Care",
        tags: ["heart attack", "stroke", "choking", "burns", "allergies", "poisoning", "fainting", "paralysis"],
        icon: "BriefcaseMedical",
        recommendedQuestions: ["What to do during heart attack?", "How to recognize stroke symptoms fast?", "When should emergency services be called?", "How to perform CPR correctly?"],
      },
    ],
  },
  skin: {
    id: 7,
    name: "Skin & Beauty",
    icon: "Sparkles",
    gradient: ["#F472B6", "#DB2777"],
    isPopular: false,
    bgColor: "#FCE7F3",
    color: "#DB2777",
    categories: [
      {
        id: 1,
        title: "Acne & Blemishes",
        tags: ["pimples", "blackheads", "scars", "oily skin"],
        icon: "User",
        recommendedQuestions: ["Sudden adult acne causes?", "Is popping pimples harmful?", "Diet influence on acne?", "Best treatments for stubborn acne?"],
      },
      {
        id: 2,
        title: "Dryness & Sensitivity",
        tags: ["dry skin", "eczema", "irritation", "allergies"],
        icon: "Droplet",
        recommendedQuestions: ["Sudden skin itching causes?", "Allergy versus fungal rash?", "Seasonal rash flare-ups why?", "How to soothe sensitive skin?"],
      },
      {
        id: 3,
        title: "Pigmentation & Tone",
        tags: ["uneven tone", "dark spots", "tanning", "melasma"],
        icon: "Palette",
        recommendedQuestions: ["What causes uneven skin tone?", "How to reduce hyperpigmentation naturally?", "Does sun exposure darken skin tone?", "Best products for brightening skin?"],
      },
      {
        id: 4,
        title: "Anti-Aging & Renewal",
        tags: ["wrinkles", "fine lines", "collagen", "firmness"],
        icon: "Sparkles",
        recommendedQuestions: ["When does skin aging start?", "Is daily sunscreen necessary?", "Hydration improves skin appearance?", "What's an effective anti-aging routine?"],
      },
      {
        id: 5,
        title: "Infections & Rashes",
        tags: ["fungal infection", "rashes", "itching", "redness"],
        icon: "Bandage",
        recommendedQuestions: ["How to identify fungal skin infections?", "When are skin rashes contagious?", "Best treatment for recurring skin infections?", "How to prevent skin infections?"],
      },
      {
        id: 6,
        title: "Hair & Scalp Care",
        tags: ["dandruff", "hair fall", "itchy scalp", "oily scalp"],
        icon: "Scissors",
        recommendedQuestions: ["Stress causing hair loss?", "Dandruff or dry scalp?", "Is daily oiling necessary?", "How to promote healthy hair growth?"],
      },
    ],
  },
  addiction: {
    id: 8,
    name: "Addiction",
    icon: "Ban",
    gradient: ["#FB923C", "#EA580C"],
    isPopular: true,
    bgColor: "#FEE2E2",
    color: "#DC2626",
    categories: [
      {
        id: 1,
        title: "Substance Addiction",
        tags: ["alcohol", "drugs", "nicotine", "prescription misuse"],
        icon: "Pill",
        recommendedQuestions: ["How does substance addiction begin?", "Early signs of substance dependence?", "When to seek professional help?", "What are effective recovery strategies?"],
      },
      {
        id: 2,
        title: "Digital Addiction",
        tags: ["phone", "social media", "gaming", "internet"],
        icon: "Smartphone",
        recommendedQuestions: ["How to identify phone addiction?", "Why scrolling feels endless?", "Practical digital detox steps?", "How to build healthier tech habits?"],
      },
      {
        id: 3,
        title: "Food & Sugar Addiction",
        tags: ["binge eating", "junk food", "sugar cravings"],
        icon: "Pizza",
        recommendedQuestions: ["Why is sugar so addictive?", "Signs of emotional eating addiction?", "How to control sugar cravings?", "What replaces unhealthy eating patterns?"],
      },
      {
        id: 4,
        title: "Work & Productivity Addiction",
        tags: ["workaholism", "burnout", "overworking"],
        icon: "Briefcase",
        recommendedQuestions: ["Can overworking harm mental health?", "Signs of work addiction burnout?", "How to set healthy work boundaries?", "How to achieve work-life balance?"],
      },
      {
        id: 5,
        title: "Recovery & Relapse Support",
        tags: ["withdrawal", "support systems", "healing", "motivation"],
        icon: "Heart",
        recommendedQuestions: ["How to prevent addiction relapse?", "What support helps long-term recovery?", "How to replace addictive habits?", "Where to find addiction support groups?"],
      },
    ],
  },
  relationship: {
    id: 15,
    name: "Relationship",
    icon: "Users",
    gradient: ["#F9A8D4", "#EC4899"],
    isPopular: false,
    bgColor: "#FCE7F3",
    color: "#DB2777",
    categories: [
      {
        id: 1,
        title: "Dating & Attraction",
        tags: ["flirting", "first dates", "chemistry", "building connection", "online dating"],
        icon: "Heart",
        recommendedQuestions: ["How to assess dating compatibility?", "Common online dating red flags?", "What does ghosting really mean?", "How to build genuine connections?"],
      },
      {
        id: 2,
        title: "Marriage & Commitment",
        tags: ["long-term relationships", "trust", "compatibility", "intimacy", "partnership goals"],
        icon: "Circle",
        recommendedQuestions: ["Managing expectation differences successfully?", "Common causes of marital conflict?", "When should couples therapy start?", "How to strengthen marriage bonds?"],
      },
      {
        id: 3,
        title: "Communication & Conflict",
        tags: ["arguments", "boundaries", "emotional expression", "listening", "healing fights"],
        icon: "MessageCircle",
        recommendedQuestions: ["How to communicate without arguments?", "Healthy ways to resolve conflicts?", "Why conflicts repeat in relationships?", "How to practice active listening?"],
      },
      {
        id: 4,
        title: "Family & Parenting",
        tags: ["family dynamics", "in-laws", "children", "co-parenting", "work-life balance"],
        icon: "Home",
        recommendedQuestions: ["How to manage family boundaries?", "Handling parenting disagreements between partners?", "How family stress affects children?", "How to create a supportive family environment?"],
      },
      {
        id: 5,
        title: "Breakups & Healing",
        tags: ["moving on", "self-worth", "letting go", "recovery", "closure", "self-love"],
        icon: "HeartOff",
        recommendedQuestions: ["How to heal after a breakup?", "How long does breakup grief last?", "When is dating again healthy?", "How to rebuild self-esteem after breakup?"],
      },
    ],
  },
  // finance: {
  //   id: 9,
  //   name: "Finance",
  //   icon: "Coins",
  //   gradient: ["#6EE7B7", "#10B981"],
  //   isPopular: false,
  //   bgColor: "#D1FAE5",
  //   color: "#059669",
  //   categories: [
  //     {
  //       id: 1,
  //       title: "Budgeting & Saving",
  //       tags: ["personal finance", "budget planning", "saving goals", "spending control"],
  //       icon: "Wallet",
  //       recommendedQuestions: ["Monthly budget kaise banaye?", "Savings ka target kaise set kare?", "Unnecessary expenses kaise avoid kare?"],
  //     },
  //     {
  //       id: 2,
  //       title: "Investments",
  //       tags: ["mutual funds", "stocks", "bonds", "gold", "real estate"],
  //       icon: "TrendingUp",
  //       recommendedQuestions: ["Mutual fund FD se better kab hota hai?", "SIP kis income pe start karni chahiye?", "Market girne par investment band kare ya continue?"],
  //     },
  //     {
  //       id: 3,
  //       title: "Insurance Planning",
  //       tags: ["health insurance", "life insurance", "vehicle insurance"],
  //       icon: "ShieldCheck",
  //       recommendedQuestions: ["Health insurance kab lena best hota hai?", "Term insurance aur ULIP me difference?", "Insurance cover kitna hona chahiye?"],
  //     },
  //     {
  //       id: 4,
  //       title: "Loans & Credit",
  //       tags: ["home loan", "education loan", "credit score", "EMI management"],
  //       icon: "CreditCard",
  //       recommendedQuestions: ["Home loan EMI safe limit kitni hoti hai?", "Credit card limit badhwana safe hota hai?", "Credit card se credit score kaise improve kare?"],
  //     },
  //     {
  //       id: 5,
  //       title: "Tax & Compliance",
  //       tags: ["income tax", "returns", "deductions", "filing"],
  //       icon: "FileText",
  //       recommendedQuestions: ["ITR filing kab compulsory hai?", "Tax saving ke simple tareeke?", "Tax deductions kaunse claim kar sakte hain?"],
  //     },
  //   ],
  // },
  // tax: {
  //   id: 10,
  //   name: "CA Taxes",
  //   icon: "Calculator",
  //   gradient: ["#34D399", "#059669"],
  //   isPopular: false,
  //   bgColor: "#D1FAE5",
  //   color: "#059669",
  //   categories: [
  //     {
  //       id: 1,
  //       title: "Income Tax",
  //       tags: ["returns", "TDS", "advance tax", "exemptions"],
  //       icon: "FileText",
  //       recommendedQuestions: ["Income tax return kaise file kare?", "TDS refund kaise claim kare?", "Tax exemption limit kya hai?"],
  //     },
  //     {
  //       id: 2,
  //       title: "GST & Indirect Taxes",
  //       tags: ["GST filing", "input credit", "rates", "e-invoice"],
  //       icon: "Receipt",
  //       recommendedQuestions: ["GST return late hone par penalty?", "Input tax credit kab reject hota hai?", "E-invoice kis par mandatory hota hai?"],
  //     },
  //     {
  //       id: 3,
  //       title: "Audit & Accounting",
  //       tags: ["bookkeeping", "financial statements", "audit reports"],
  //       icon: "ClipboardList",
  //       recommendedQuestions: ["Audit kyu hota hai?", "Basic accounting kaise sikhe?", "Financial statements kaise padhe?"],
  //     },
  //     {
  //       id: 4,
  //       title: "Business Compliance",
  //       tags: ["startup registration", "licenses", "certifications", "ROC filing"],
  //       icon: "Briefcase",
  //       recommendedQuestions: ["Company incorporation ka process kya hota hai?", "Startup India certificate ka kya fayda?", "Annual compliance miss ho jaye to kya hota hai?"],
  //     },
  //     {
  //       id: 5,
  //       title: "Tax Planning & Optimization",
  //       tags: ["deductions", "rebates", "financial planning", "savings"],
  //       icon: "TrendingUp",
  //       recommendedQuestions: ["Legal tax saving ke best tareeke kaunse hain?", "Advance tax kab bharna hota hai?", "Cash transaction ki legal limit kya hai?"],
  //     },
  //   ],
  // },
  // lawyer: {
  //   id: 11,
  //   name: "Lawyer",
  //   icon: "Scale",
  //   gradient: ["#93C5FD", "#3B82F6"],
  //   isPopular: false,
  //   bgColor: "#BFDBFE",
  //   color: "#2563EB",
  //   categories: [
  //     {
  //       id: 1,
  //       title: "Legal Advice & Consultation",
  //       tags: ["legal help", "rights", "law queries", "case guidance"],
  //       icon: "UserCheck",
  //       recommendedQuestions: ["Legal notice ka matlab kya hai?", "Apne rights kaise protect kare?", "Lawyer kab hire karna chahiye?"],
  //     },
  //     {
  //       id: 2,
  //       title: "Contracts & Agreements",
  //       tags: ["rental agreements", "business contracts", "NDAs", "partnership deeds"],
  //       icon: "FileText",
  //       recommendedQuestions: ["Contract sign karne se pehle kya check kare?", "Agreement breach hone par kya kare?", "Rental agreement ke important clauses?"],
  //     },
  //     {
  //       id: 3,
  //       title: "Family & Marriage Law",
  //       tags: ["divorce", "alimony", "child custody", "domestic rights"],
  //       icon: "Home",
  //       recommendedQuestions: ["Divorce me settlement kaise hota hai?", "Child custody ka decision kaise hota hai?", "Domestic dispute me legal options kya hain?"],
  //     },
  //     {
  //       id: 4,
  //       title: "Criminal & Civil Matters",
  //       tags: ["FIR", "bail", "consumer rights", "disputes"],
  //       icon: "Gavel",
  //       recommendedQuestions: ["FIR online kaise file kare?", "Traffic challan galat aaye to kya kare?", "Refund deny ho to legal step kya hai?"],
  //     },
  //     {
  //       id: 5,
  //       title: "Corporate & Startup Law",
  //       tags: ["company formation", "compliance", "intellectual property", "labor laws"],
  //       icon: "Building",
  //       recommendedQuestions: ["Startup ke liye legal structure kaunsa best?", "Intellectual property kaise protect kare?", "Co-founder agreement me kya include kare?"],
  //     },
  //     {
  //       id: 6,
  //       title: "Property & Real Estate Law",
  //       tags: ["land disputes", "registration", "leases", "property transfer"],
  //       icon: "MapPin",
  //       recommendedQuestions: ["Property dispute kaise avoid kare?", "Registry aur agreement me difference?", "Property fraud kaise pehchane?"],
  //     },
  //   ],
  // },
  // government: {
  //   id: 12,
  //   name: "Government",
  //   icon: "Landmark",
  //   gradient: ["#60A5FA", "#2563EB"],
  //   isPopular: false,
  //   bgColor: "#DBEAFE",
  //   color: "#2563EB",
  //   categories: [
  //     {
  //       id: 1,
  //       title: "Documents & IDs",
  //       tags: ["Aadhaar", "PAN", "passport", "voter ID", "driving license"],
  //       icon: "IdCard",
  //       recommendedQuestions: ["Aadhaar update me kitna time lagta hai?", "PAN–Aadhaar link miss ho jaye to?", "Birth certificate error kaise correct kare?"],
  //     },
  //     {
  //       id: 2,
  //       title: "Government Schemes",
  //       tags: ["PMAY", "PM Kisan", "pensions", "education aid", "loans"],
  //       icon: "Hand",
  //       recommendedQuestions: ["Eligible scheme kaise identify kare?", "Subsidy milne me delay kyu hota hai?", "Scholarship reject hone ke reasons?"],
  //     },
  //     {
  //       id: 3,
  //       title: "Public Grievances & Rights",
  //       tags: ["RTI", "consumer complaints", "citizen rights", "ombudsman"],
  //       icon: "Megaphone",
  //       recommendedQuestions: ["RTI ka reply na aaye to kya kare?", "Noise pollution complaint kaha kare?", "Cyber crime report kaise kare?"],
  //     },
  //     {
  //       id: 4,
  //       title: "Education & Employment Services",
  //       tags: ["scholarships", "skill development", "government jobs"],
  //       icon: "School",
  //       recommendedQuestions: ["Government scholarship kaise apply kare?", "Sarkari naukri ke liye best preparation?", "Skill development schemes konsi hain?"],
  //     },
  //     {
  //       id: 5,
  //       title: "Business & Licenses",
  //       tags: ["MSME", "GST registration", "startup India", "trade license"],
  //       icon: "Building",
  //       recommendedQuestions: ["Business registration kaise kare?", "Trade license lene ka process?", "MSME certificate ke benefits?"],
  //     },
  //     {
  //       id: 6,
  //       title: "Citizen Welfare & Safety",
  //       tags: ["women helpline", "senior citizen care", "public safety", "emergency contacts"],
  //       icon: "Shield",
  //       recommendedQuestions: ["Women helpline number kya hai?", "Emergency me kisko contact kare?", "Senior citizen welfare schemes?"],
  //     },
  //   ],
  // },
  // career: {
  //   id: 13,
  //   name: "Career Coach",
  //   icon: "Briefcase",
  //   gradient: ["#FCD34D", "#F59E0B"],
  //   isPopular: true,
  //   bgColor: "#FFEDD5",
  //   color: "#EA580C",
  //   categories: [
  //     {
  //       id: 1,
  //       title: "Education",
  //       tags: ["school", "college", "skill development", "vocational courses", "admissions", "scholarships"],
  //       icon: "BookOpen",
  //       recommendedQuestions: ["12th ke baad best course konsa?", "Scholarship kaise apply kare?", "Online courses worth hai kya?"],
  //     },
  //     {
  //       id: 2,
  //       title: "Employment",
  //       tags: ["jobs", "government vacancies", "internships", "career guidance", "professional growth"],
  //       icon: "Briefcase",
  //       recommendedQuestions: ["Job change ka sahi time kaise pehchane?", "Resume short rakhe ya detailed?", "Interview me gap year kaise explain kare?"],
  //     },
  //     {
  //       id: 3,
  //       title: "Business & Entrepreneurship",
  //       tags: ["startups", "MSME", "manufacturing", "agriculture", "tenders", "GEM"],
  //       icon: "Lightbulb",
  //       recommendedQuestions: ["Startup kaise shuru kare?", "Business idea validate kaise kare?", "Funding kaha se mile?"],
  //     },
  //     {
  //       id: 4,
  //       title: "Self-Employed",
  //       tags: ["freelancing", "consultants", "micro-businesses", "local services", "home-based businesses", "professionals"],
  //       icon: "UserCheck",
  //       recommendedQuestions: ["Freelancing me clients kaise dhunde?", "Pricing kitni rakhni chahiye?", "Clients se payment time pe kaise le?"],
  //     },
  //   ],
  // },
  // shopping: {
  //   id: 14,
  //   name: "Shopping",
  //   icon: "ShoppingBag",
  //   gradient: ["#998bd3ff", "#8B5CF6"],
  //   isPopular: false,
  //   bgColor: "#EDE9FE",
  //   color: "#7C3AED",
  //   categories: [
  //     {
  //       id: 1,
  //       title: "Gadgets",
  //       tags: ["electronics", "mobiles", "laptops", "tablets", "smartwatches", "accessories"],
  //       icon: "Smartphone",
  //       recommendedQuestions: ["Phone me camera ya processor kya choose kare?", "Refurbished gadgets safe hote hain kya?", "Fake reviews kaise identify kare?"],
  //     },
  //     {
  //       id: 2,
  //       title: "Furniture",
  //       tags: ["home", "office", "decor", "storage", "outdoor", "modular solutions"],
  //       icon: "Armchair",
  //       recommendedQuestions: ["Furniture quality kaise check kare?", "Small space ke liye best furniture?", "Solid wood vs engineered wood?"],
  //     },
  //     {
  //       id: 3,
  //       title: "Apparel",
  //       tags: ["men", "women", "kids", "ethnic", "sportswear", "accessories"],
  //       icon: "ShoppingBag",
  //       recommendedQuestions: ["Online shopping me size kaise choose kare?", "Budget me fashionable kaise rahe?", "Fabric quality kaise pehchane?"],
  //     },
  //     {
  //       id: 4,
  //       title: "Automotive",
  //       tags: ["cars", "bikes", "scooters", "spare parts", "accessories", "EVs"],
  //       icon: "Car",
  //       recommendedQuestions: ["Petrol vs diesel vs EV kaise decide kare?", "Used car lete waqt kya check kare?", "Service centre overcharge kaise pehchane?"],
  //     },
  //     {
  //       id: 5,
  //       title: "Home & Kitchen",
  //       tags: ["appliances", "cookware", "furniture", "lighting", "storage"],
  //       icon: "Home",
  //       recommendedQuestions: ["Kitchen appliances me kya invest kare?", "Energy-efficient products kaise pehchane?", "Cookware safe aur durable kaunsa?"],
  //     },
  //   ],
  // },
    // astro: {
  //   id: 16,
  //   name: "Astro",
  //   icon: "Moon",
  //   gradient: ["#A78BFA", "#7C3AED"],
  //   isPopular: false,
  //   bgColor: "#EDE9FE",
  //   color: "#7C3AED",
  //   categories: [
  //     {
  //       id: 1,
  //       title: "Zodiac Insights",
  //       tags: ["sun signs", "moon signs", "rising signs", "horoscope", "daily predictions"],
  //       icon: "Star",
  //       recommendedQuestions: ["Daily horoscope kitna reliable hota hai?", "Career prediction kaise padhe?", "Negative horoscope ka fear kaise handle kare?"],
  //     },
  //     {
  //       id: 2,
  //       title: "Love & Compatibility",
  //       tags: ["relationship matches", "emotional chemistry", "communication styles", "trust and attraction"],
  //       icon: "Heart",
  //       recommendedQuestions: ["Kundli matching kitni important hoti hai?", "Astrology se relationship success predict hota hai?", "Manglik dosh ka real impact?"],
  //     },
  //     {
  //       id: 3,
  //       title: "Career & Growth",
  //       tags: ["career path", "success timing", "planetary support", "decision guidance"],
  //       icon: "Briefcase",
  //       recommendedQuestions: ["Career change ka sahi time kab hai?", "Job me success ke liye planetary support?", "Business start karne ka best time?"],
  //     },
  //     {
  //       id: 4,
  //       title: "Health & Energy",
  //       tags: ["mind-body balance", "spiritual healing", "planetary influence on health", "well-being cycles"],
  //       icon: "Activity",
  //       recommendedQuestions: ["Planetary positions health ko kaise affect karte?", "Energy levels kaise balance kare?", "Meditation ka best time kya hai?"],
  //     },
  //     {
  //       id: 5,
  //       title: "Life Path & Karma",
  //       tags: ["birth chart insights", "soul purpose", "past karma", "spiritual evolution"],
  //       icon: "Infinity",
  //       recommendedQuestions: ["Birth chart se life purpose kaise jane?", "Karma ka effect kaise samjhe?", "Spiritual growth me astrology ka role?"],
  //     },
  //   ],
  // },
};

